In [1]:
import numpy as np
import pandas as pd

# 1st method: From a Pandas Series
df = pd.DataFrame({
    "color":["Blue", "Red", "Pink", "Grey", "Black"],
    "list":[[1, 2], [3, 4],[5, 6],[7, 8], [9, 10]],
    "numbers": [1.1, 2.2, 3.3, 4.4, 5.5]
}, index=[1,3,5,7,9])

df

   color     list  numbers
1   Blue   [1, 2]      1.1
3    Red   [3, 4]      2.2
5   Pink   [5, 6]      3.3
7   Grey   [7, 8]      4.4
9  Black  [9, 10]      5.5

In [2]:
# 2st method: From a NumPy array


color= np.array(["Blue", "Red", "Pink", "Grey", "Black"])
list= np.empty(5, dtype=object)
list = [[1, 2], [3, 4],[5, 6],[7, 8], [9, 10]]
# print(list)
numbers=  np.array([1.1, 2.2, 3.3, 4.4, 5.5])

df = pd.DataFrame({
    "color": color,
    "list": list,
    "numbers": numbers
}, index=[1,3,5,7,9])
df

   color     list  numbers
1   Blue   [1, 2]      1.1
3    Red   [3, 4]      2.2
5   Pink   [5, 6]      3.3
7   Grey   [7, 8]      4.4
9  Black  [9, 10]      5.5

In [3]:
# columns’ types
for col in df.columns:
    print(type(df[col]))

print()

for col in df.columns:
    print(type(df[col].iloc[0]))

<class 'pandas.Series'>
<class 'pandas.Series'>
<class 'pandas.Series'>

<class 'str'>
<class 'list'>
<class 'numpy.float64'>